---
- name: Delete temporary blob container
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: delete a temp blob storage and all contents
      azure_rm_storageblob:
        resource_group: epm-ldi
        storage_account_name: storage11490
        container: "epm-ldi-aem-{{ lookup('env','CI_JOB_ID') }}"
        state: absent
        force: true
