---
# Run all tests
stages:
  - lint
  - deployment test

before_script:
  - ansible --version
  - ansible-lint --version
  - molecule --version

variables:
  GET_SOURCES_ATTEMPTS: "5"

Ansible lint:
  stage: lint
  before_script:
    - git clone https://github.com/lean-delivery/ansible-lint-rules.git ~/ansible-lint-rules
  script:
    - ansible-lint . -c .ansible-lint
  after_script:
    - rm -rf ~/ansible-lint-rules
  tags:
    - aws

AWS aem-node:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-direct
  tags:
    - aws

#Docker aem-node:
#  stage: deployment test
#  script:
#    - molecule test -s default
#  tags:
#    - aws
