---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: ec2
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-aws-centos7-aem-node-author-6.3-mongo
    profile_name: epmldi-instance-profile
    image: ami-9887c6e7
    instance_type: m5.large
    region: us-east-1
    vpc_subnet_id: subnet-05a2ef2b767afec50
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
      - rhel_family
      - aem_authors
      - aem_publishers

provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer
  playbooks:
    create: ../resources/provisioning/AWS/create.yml
    prepare: prepare.yml
    destroy: ../resources/provisioning/AWS/destroy.yml
    verify: ../resources/tests/verify.yml
  lint:
    name: ansible-lint
scenario:
  name: cloud-aws-direct-author-6.3-mongo
verifier:
  name: ansible
  lint:
    name: ansible-lint
