---
# file: tasks/add-user.yml

- name: 'create user {{ user.id }}'
  aem_user:
    id: '{{ user.id }}'
    first_name: '{{ user.first_name }}'
    last_name: '{{ user.second_name }}'
    password: '{{ user.password }}'
    groups: '{{ user.group }}'
    host: "http://localhost"
    port: "{{ aem_instance_port }}"
    admin_user: '{{ aem_admin_login }}'
    admin_password: '{{ aem_admin_password }}'
    state: present
