---
# file: tasks/add-group.yml

- name: 'add a new {{ group.name }} group'
  aem_group:
    id: '{{ group.id }}'
    name: '{{ group.name }}'
    host: '{{ group.host | default("http://localhost") }}'
    port: '{{ group.port | default("4502") }}'
    admin_user: '{{ aem_admin_login }}'
    admin_password: '{{ aem_admin_password }}'
    permissions: '{{ group.permissions | default(None) }}'
    root_groups: '{{ group.root_groups | default(None) }}'
    state: present
