---
# file: tasks/configure_stores.yml

- name: Configure data store
  block:
    - name: define data store variables
      set_fact:
        data_store_type: '{{ install_data_store_s3 | ternary("s3", "azure") }}'
        aem_install_dir: '{{ aem_home }}/crx-quickstart/install'
        # To use TarMK with the S3 Datastore, we need to start AEM using the crx3tar-nofds runmode
        aem_custom_modes: crx3tar-nofds

    - name: set variables based on data store type
      include_vars: 'data_store/{{ data_store_type }}_vars.yml'

    - name: download data store feature pack
      include_tasks: 'fetch_feature_pack.yml'

    - name: define temp_dir variable
      set_fact:
        temp_dir: '{{ tmpdir }}/{{ (data_store_file_downloaded.dest | basename | splitext)[0] }}'

    - name: create a folder crx-quickstart/install in the installation directory
      file:
        path: '{{ aem_install_dir }}'
        state: directory
        owner: '{{ aem_user }}'
        group: '{{ aem_user }}'

    - name: ensure temporary directory exists
      file:
        path: '{{ temp_dir }}'
        state: directory

    - name: extract the contents of the feature pack zip file to a temporary folder
      unarchive:
        src: '{{ data_store_file_downloaded.dest }}'
        dest: '{{ temp_dir }}'
        remote_src: true

    - name: copy jars to AEM install folder
      copy:
        src: '{{ temp_dir }}/jcr_root/libs/system/install/'
        dest: '{{ aem_install_dir }}/'
        remote_src: true
        owner: '{{ aem_user }}'
        group: '{{ aem_user }}'

    - name: copy config files to AEM install folder
      copy:
        src: '{{ temp_dir }}/jcr_root/libs/system/config/'
        dest: '{{ aem_install_dir }}/'
        remote_src: true
        owner: '{{ aem_user }}'
        group: '{{ aem_user }}'

    - name: creating PID for configuration Data Store
      template:
        src: 'datastore_{{ data_store_type }}.config.j2'
        dest: '{{ aem_install_dir + "/" + datastore_connector_pid_file }}'
        owner: '{{ aem_user }}'
        group: '{{ aem_user }}'
        mode: 0660

    - name: Debug PID file
      debug:
        msg: "{{ lookup('file', aem_install_dir + '/' + datastore_connector_pid_file) }}"
  become: true
