---
# file: tasks/configure_data_store.yml

- name: set variables based on data store type
  include_vars: 'data_store/{{ aem_datastore_type }}_vars.yml'

- name: download and unpack cloud data store connector
  include_tasks: 'feature_pack-installation.yml'
  when: aem_datastore_type == 's3' or aem_datastore_type == 'azure'

- name: creating PID for configuration Data Store
  template:
    src: 'datastore_{{ aem_datastore_type }}.config.j2'
    dest: '{{ aem_install_dir + "/" + datastore_pid_file }}'
    owner: '{{ aem_user }}'
    group: '{{ aem_user }}'
    mode: 0644
  become: true
