---
# file: tasks/configure-replication.yml

- name: "check if an agent for {{ publisher }} host created"
  uri:
    url: "{{ aem_rest_link }}/etc/replication/agents.author/{{ publisher|replace('.','-')|lower() }}.html"
    method: GET
    user: '{{ aem_admin_login }}'
    password: '{{ aem_admin_password }}'
    force_basic_auth: True
    status_code: 200, 404, -1
  register: checkRequest

- name: "create agent for {{ publisher }} if dont exist"
  uri:
    url: "{{ aem_rest_link }}/bin/wcmcommand"
    method: POST
    user: '{{ aem_admin_login }}'
    password: '{{ aem_admin_password }}'
    force_basic_auth: True
    body: "cmd=createPage&charset=UTF-8&parentPath=/etc/replication/agents.author&title={{ publisher|replace('.','-')|lower() }}&label={{ publis\
her|replace('.','-')|lower() }}&template=/libs/cq/replication/templates/agent"
  register: agentCreate
  until: (agentCreate is succeeded)
  retries: 100
  delay: 5
  when: checkRequest.status == 404

- name: "check {{ publisher }} agent configuration"
  uri:
    url: "{{ aem_rest_link }}/etc/replication/agents.author/{{ publisher|replace('.','-')|lower() }}/jcr:content"
    method: POST
    user: '{{ aem_admin_login }}'
    password: '{{ aem_admin_password }}'
    force_basic_auth: True
    body: "enabled=true&transportUri=http://{{ hostvars[publisher]['inventory_hostname'] }}:{{ aem_instance_port }}/bin/recei\
ve?sling:authRequestLogin=1&transportUser={{ aem_admin_login }}&transportPassword={{ aem_admin_password\
 }}&retryDelay=60000&logLevel=info&serializationType=durbo&jcr:description=Replication agent for {{ publisher }} node (publish type)"
  register: agentConfigure
  until: (agentConfigure is succeeded)
  retries: 100
  delay: 5
