---
# file: tasks/configure.yml

- name: set new password if it was changed
  set_fact:
    aem_admin_password: '{{ aem_new_admin_password }}'
  when: aem_change_default_admin_password


- name: 'ensure that systemd {{ aem_service_name }} script is ok'
  template:
    src: aem.service.j2
    dest: '/etc/systemd/system/{{ aem_service_name }}.service'
    mode: 0644
  become: True
  notify:
  - stop aem
  - start aem
  - load aem
- meta: flush_handlers
