---
# file: tasks/configure-replication.yml

- name: "Create/update agent for {{ hostvars[host]['inventory_hostname'] }} (publish type)"
  aem_agent:
    name: "{{ publisher|replace('.','-')|lower() }}-publisher"
    state: present
    title: "{{ publisher|replace('.','-')|lower() }}"
    folder: 'agents.author'
    template: "/libs/cq/replication/templates/agent"
    transport_uri: "http://{{ hostvars[publisher]['inventory_hostname'] }}:{{ hostvars[publisher]['aem_instance_port']\
                    | default(aem_instance_port) }}/bin/receive?sling:authRequestLogin=1"
    transport_user: "{{ aem_admin_login }}"
    transport_password: "{{ aem_admin_password }}"
    log_level: error
    serialization_type: durbo
    description: "Replication agent for {{ publisher }} node (publish type)"
    admin_user: '{{ aem_admin_login }}'
    admin_password: '{{ aem_admin_password }}'
    retry_delay: 60000
    host: "http://localhost"
    port: 4502
