---
# file: tasks/configure-replication.yml

- name: "check if an agent for {{ hostvars[host]['inventory_hostname'] }} host created"
  uri:
    url: "{{ aemRESTLink }}/etc/replication/agents.{{ aemInstanceType }}/{{ hostvars[host]['inventory_hostname']|replace('.','-')|lower() }}.html"
    method: GET
    user: '{{ aemAdminLogin }}'
    password: '{{ aemAdminPassword }}'
    force_basic_auth: yes
    status_code: 200, 404, -1
  register: checkRequest

- name: "create agent for {{ hostvars[host]['inventory_hostname'] }} if dont exist"
  uri:
    url: "{{ aemRESTLink }}/bin/wcmcommand"
    method: POST
    user: '{{ aemAdminLogin }}'
    password: '{{ aemAdminPassword }}'
    force_basic_auth: yes
    body: "cmd=createPage&charset=UTF-8&parentPath=/etc/replication/agents.{{ aemInstanceType }}&label={{ hostvars[host]['inventory_hostname']|replace('.','-')|lower() }}&title={{ hostvars[host]['inventory_hostname']|replace('.','-')|lower() }}&template=/libs/cq/replication/templates/agent"
  register: agentCreate
  until: (agentCreate is succeeded)
  retries: 100
  delay: 5
  when: checkRequest.status == 404

- name: prepare to rewrite baseAgentBody if webServerSSL is true
  set_fact:
    webServerPort: "{{ hostvars[host]['webServerHTTPsPort'] }}"
  when: hostvars[host]['webServerSSL']

- name: prepare to rewrite baseAgentBody if webServerSSL is false
  set_fact:
    webServerPort: "{{ hostvars[host]['webServerHTTPPort'] }}"
  when: not hostvars[host]['webServerSSL']

- name: rewrite baseAgentBody
  set_fact:
    baseAgentBody: "{{ baseAgentBody }}&transportUri=http://{{ hostvars[host]['inventory_hostname'] }}:{{ webServerPort }}/dispatcher/invalidate.cache&retryDelay=60000&logLevel=error&serializationType=flush&jcr:description=Dispatcher flush agent for {{ hostvars[host]['inventory_hostname'] }} node (flush type)"

- name: set agent body for author instance
  set_fact:
    agentBody: "{{ baseAgentBody }}&enabled=false"
  when: aemInstanceType == 'author'

- name: set agent body for publish instance
  set_fact:
    agentBody: "{{ baseAgentBody }}&enabled=true"
  when: aemInstanceType == 'publish'

- name: "check {{ hostvars[host]['inventory_hostname'] }} agent configuration"
  uri:
    url: "{{ aemRESTLink }}/etc/replication/agents.{{ aemInstanceType }}/{{ hostvars[host]['inventory_hostname']|replace('.','-')|lower() }}/jcr:content"
    method: POST
    user: '{{ aemAdminLogin }}'
    password: '{{ aemAdminPassword }}'
    force_basic_auth: yes
    body: '{{ agentBody }}'
  register: agentConfigure
  until: (agentConfigure is succeeded)
  retries: 100
  delay: 5
