---
- name: 'ensure that {{ cq_file_name }} file is downloaded (s3 transport)'
  aws_s3:
    bucket: 'aemartifacts'
    object: '/6.5/aem.jar'
    dest: '{{ aem_home }}/{{ cq_file_name }}.jar'
    aws_access_key: '{{ transport_s3_aws_access_key }}'
    aws_secret_key: '{{ transport_s3_aws_secret_key }}'
    mode: get
    overwrite: different
    ignore_nonexistent_bucket: true
  retries: 5
  delay: 2

- name: 'protecting aem jar file'
  file:
    path: '{{ aem_home }}/{{ cq_file_name }}.jar'
    owner: '{{ aem_user }}'
    group: '{{ aem_user }}'
    mode: '0640'

- name: 'ensure that AEM licence file is downloaded (s3 transport)'
  aws_s3:
    bucket: '{{ transport_s3_bucket }}'
    object: '{{ license_transport_s3_path }}'
    dest: '{{ aem_home }}/license.properties'
    aws_access_key: '{{ transport_s3_aws_access_key }}'
    aws_secret_key: '{{ transport_s3_aws_secret_key }}'
    mode: get
    overwrite: different
    ignore_nonexistent_bucket: true
  retries: 5
  delay: 2

- name: 'protecting license file'
  file:
    path: '{{ aem_home }}/license.properties'
    owner: '{{ aem_user }}'
    group: '{{ aem_user }}'
    mode: '0640'
