---
# file: tasks/fetch_feature_pack.yml

# Feature pack(s) will be downloaded from Adobe Repository
# https://repo.adobe.com/nexus/content/groups/public/com/adobe/
- name: download data store feature pack
  block:
    - name: fetch checksum file
      uri:
        url: '{{ adobe_repo_feature_pack_md5_link }}'
        return_content: true
      register: feature_pack_checksum
      retries: 5
      delay: 3

    - name: Download feature pack for data store
      get_url:
        url: '{{ adobe_repo_feature_pack_link }}'
        dest: '{{ tmpdir }}'
        checksum: 'md5:{{ feature_pack_checksum.content }}'
      register: data_store_file_downloaded
      retries: 5
      delay: 3
