---
# file: tasks/install.yml

- name: 'ensure that {{ cq_file_name }} file is downloaded (web transport)'
  get_url:
    url: '{{ full_aem_web_transport_link }}'
    dest: '{{ aem_home }}/{{ cq_file_name }}.jar'
    owner: '{{ aem_user }}'
    group: '{{ aem_user }}'
    mode: 0640
  become: true

- name: ensure that AEM licence file is downloaded (web transport)
  get_url:
    url: '{{ full_license_web_transport_link }}'
    dest: '{{ aem_home }}/license.properties'
    owner: '{{ aem_user }}'
    group: '{{ aem_user }}'
    mode: 0640
  become: true

- name: ensure that Jolokia agent is downloaded
  get_url:
    url: '{{ jolokia_agent_url }}'
    dest: '{{ aem_home }}/jolokia-jvm-1.6.2-agent.jar'
    owner: '{{ aem_user }}'
    group: '{{ aem_user }}'
    mode: 0640
  become: true
  when: jolokia_agent is defined
