---
# file: tasks/install.yml

- name: "ensure that {{ cqFileName }} file is downloaded"
  get_url:
    url: '{{ ftpServerLink }}/aem.jar'
    dest: '{{ aemHome }}/{{ cqFileName }}.jar'
    owner: '{{ aemUser }}'
    group: '{{ aemUser }}'
    mode: 0640

- name: ensure that AEM licence file is downloaded
  get_url:
    url: '{{ ftpServerLink }}/license.properties'
    dest: '{{ aemHome }}/license.properties'
    owner: '{{ aemUser }}'
    group: '{{ aemUser }}'
    mode: 0640

- name: extract AEM jar file if crx-quickstart folder doesn't exist
  command: "java -jar {{ aemHome }}/{{ cqFileName }}.jar -unpack"
  args:
    creates: '{{ aemHome }}/crx-quickstart/bin'
    chdir: '{{ aemHome }}'

- name: ensure that all permissions for home aem dir is correct
  file:
    path: '{{ aemHome }}/crx-quickstart'
    state: directory
    owner: '{{ aemUser }}'
    group: '{{ aemUser }}'
    recurse: yes

- name: ensure that subsys directory exists
  file:
    path: '/var/lock/subsys'
    state: directory
    recurse: yes

- name: creating init script for AEM instance
  template:
    src: aem.j2
    dest: '/usr/bin/{{ aemServiceName }}'
    owner: root
    group: root
    mode: 0755

- name: creating systemd script for AEM instance
  template:
    src: aem.service.j2
    dest: '/usr/lib/systemd/system/{{ aemServiceName }}.service'
    owner: root
    group: root
    mode: 0644

- name: fix start script for 5.5
  template:
    src: start5.5.j2
    dest: '{{ aemHome }}/crx-quickstart/bin/start'
    owner: '{{ aemUser }}'
    group: '{{ aemUser }}'
    mode: 0755
  when: "aemVersion == '5.5' or aemVersion == 5.5"

- name: start and enable aem service
  service:
    name: '{{ aemServiceName }}'
    enabled: yes
    state: started
  notify:
  - firstload aem
- meta: flush_handlers

- block:
  - name: change user password (step 1)
    uri:
      url: '{{ aemRESTLink }}/bin/querybuilder.json?path=/home/users&1_property=rep:principalName&1_property.value={{ aemAdminLogin }}&p.limit=-1'
      method: GET
      user: '{{ aemAdminLogin }}'
      password: '{{ aemAdminPassword }}'
      force_basic_auth: yes
      return_content: yes
      ignore_errors: True
    register: userCRXPath
  - name: change user password (step 2)
    uri:
      url: '{{ aemRESTLink }}/crx/explorer/ui/setpassword.jsp'
      method: POST
      user: '{{ aemAdminLogin }}'
      password: '{{ aemAdminPassword }}'
      force_basic_auth: yes
      body: 'plain={{ aemNewAdminPassword }}&verify={{ aemNewAdminPassword }}&old={{ aemAdminPassword }}&Path={{ userCRXPath.json.hits[0].path }}'
      ignore_errors: True
  - name: set new password
    set_fact:
      aemAdminPassword: '{{ aemNewAdminPassword }}'
  when: aemChangeDefaultAdminPassword

- name: fix AEM bug with nosamplecontent
  uri:
    url: '{{ aemRESTLink }}/apps/system/config/org.apache.sling.jcr.davex.impl.servlets.SlingDavExServlet'
    method: POST
    user: '{{ aemAdminLogin }}'
    password: '{{ aemAdminPassword }}'
    force_basic_auth: yes
    follow_redirects: safe
    body: 'jcr:primaryType=sling:OsgiConfig&alias=/crx/server&dav.create-absolute-uri=true&dav.create-absolute-uri@TypeHint=Boolean'
    status_code: 201, 200, 500
    ignore_errors: True
  when: aemNoSampleContent