---
# file: tasks/main.yml

- name: set facts
  include: set_facts.yml
- name: pre installation
  include: pre-install.yml

- name: check if service was installed before
  stat:
    path: '{{ aemFile }}'
  register: aem_done

- block:
  - name: installation
    include: '{{ tasksPath }}/install.yml'
  - name: save successfull installation in file
    file:
      path: '{{ aemFile }}'
      state: touch
  when: aem_done.stat.exists == false

- name: configuration
  include: configure.yml
- name: package installation
  include: '{{ tasksPath }}/package-installation.yml aemPackage={{ item }}'
  with_items: '{{ aemPackages }}'
  when: aemPackages|length > 0

# Configure replication if this is AEM Authoring instance
- name: replication configuration
  include: replication.yml

# Create additional groups
- name: aem groups creation
  include: '{{ tasksPath }}/add-group.yml group={{ item }}'
  with_items: '{{ aemGroups }}'
  when: aemGroups|length > 0

# # Create additional users
- name: aem users creation
  include: '{{ tasksPath }}/add-user.yml user={{ item }}'
  with_items: '{{ aemUsers }}'
  when: aemUsers|length > 0