---
# file: tasks/main.yml

- name: set facts
  include_tasks: set_facts.yml

- name: pre installation
  include_tasks: pre-install.yml

- name: check if service was installed before
  stat:
    path: '{{ aem_file }}'
  register: aem_done

- block:
  - name: installation
    include_tasks: '{{ tasks_path }}/install.yml'

  - name: save successfull installation in file
    file:
      path: '{{ aem_file }}'
      state: touch
    become: True
  when: not aem_done.stat.exists

- name: configuration
  include_tasks: configure.yml

- name: package installation
  include: '{{ tasks_path }}/package-installation.yml  aem_package={{ item }}'
  loop: '{{ aem_packages }}'
  when: aem_packages|length > 0

# Configure enable ssl and install ssl cert/key
- name: replication configuration
  include_tasks: activate-ssl-port.yml
  when: aem_ssl_enable

# Configure flush/replication agents
- name: replication configuration
  include_tasks: replication.yml
  when: replication_enabled

# Create additional groups
- name: aem groups creation
  include: '{{ tasks_path }}/add-group.yml group={{ item }}'
  loop: '{{ aem_groups }}'
  when: aem_groups|length > 0

 # Create additional users
- name: aem users creation
  include: '{{ tasks_path }}/add-user.yml user={{ item }}'
  loop: '{{ aem_users }}'
  when: aem_users|length > 0
