---
# file: tasks/main.yml

- name: set facts
  include: set_facts.yml
- name: pre installation
  include: pre-install.yml

- name: check if service was installed before
  stat:
    path: '{{ aem_file }}'
  register: aem_done

- block:
  - name: installation
    include: '{{ tasks_path }}/install.yml'
  - name: save successfull installation in file
    file:
      path: '{{ aem_file }}'
      state: touch
  when: aem_done.stat.exists == false

- name: configuration
  include: configure.yml
- name: package installation
  include: '{{ tasks_path }}/package-installation.yml aem_package={{ item }}'
  with_items: '{{ aem_packages }}'
  when: aem_packages|length > 0

# Configure replication if this is AEM Authoring instance
- name: replication configuration
  include: replication.yml

# Create additional groups
- name: aem groups creation
  include: '{{ tasks_path }}/add-group.yml group={{ item }}'
  with_items: '{{ aem_groups }}'
  when: aem_groups|length > 0

# # Create additional users
- name: aem users creation
  include: '{{ tasks_path }}/add-user.yml user={{ item }}'
  with_items: '{{ aem_users }}'
  when: aem_users|length > 0