---
# file: tasks/pre_install.yml

- name: ensure that aem group is configured
  group:
    name: '{{ aem_group }}'
    gid: '{{ aem_group_id }}'
  become: true

- name: ensure that aem user is configured
  user:
    name: '{{ aem_user }}'
    uid: '{{ aem_user_id }}'
    groups:
      - '{{ aem_group }}'
    append: true
    comment: 'AEM user'
  become: true

- name: ensure that root AEM directory is present
  file:
    path: '{{ aem_root }}'
    owner: '{{ aem_user }}'
    group: '{{ aem_user }}'
    mode: 0775
    state: directory
  become: true

- name: ensure that directory for AEM home dir is present
  file:
    path: '{{ aem_home }}'
    owner: '{{ aem_user }}'
    group: '{{ aem_user }}'
    mode: 0775
    state: directory
  become: true

- name: Configure system
  include_tasks: '{{ platform }}'
  with_first_found:
    - 'system/{{ ansible_os_family }}.yml'
    - system/not-supported.yml
  loop_control:
    loop_var: platform

- name: install python boto3
  pip:
    name: boto3
    executable: '{{ pip_executable }}'
  when: download_transport == "s3"
  retries: 3
  register: result
  until: result is success
  become: true
