---
# file: tasks/pre_install.yml

- name: ensure that aem group is configured
  group:
    name: '{{ aem_group }}'
    gid: '{{ aem_group_id }}'
  become: True

- name: ensure that aem user is configured
  user:
    name: '{{ aem_user }}'
    uid: '{{ aem_user_id }}'
    groups:
      - '{{ aem_group }}'
    append: True
    comment: 'AEM user'
  become: True

- name: ensure that root AEM directory is present
  file:
    path: '{{ aem_root }}'
    owner: '{{ aem_user }}'
    group: '{{ aem_user }}'
    mode: 0775
    state: directory
  become: True

- name: ensure that directory for AEM home dir is present
  file:
    path: '{{ aem_home }}'
    owner: '{{ aem_user }}'
    group: '{{ aem_user }}'
    mode: 0775
    state: directory
  become: True

- name: install pip to Debian OS family
  apt:
    name: python-pip
    update_cache: True
  when: ansible_facts['os_family'] == "Debian"
  retries: 3
  register: result
  until: result is success
  become: True

- name: install python requests
  pip:
    name: requests
  when: ansible_facts['os_family'] == "Debian"
  retries: 3
  register: result
  until: result is success
  become: True
