---
# file: tasks/pre_install.yml

- name: ensure that aem group is configured
  group:
    name: '{{ aem_group }}'
    gid: '{{ aem_group_id }}'

- name: ensure that aem user is configured
  user:
    name: '{{ aem_user }}'
    uid: '{{ aem_user_id }}'
    groups:
      - '{{ aem_group }}'
    append: True
    comment: 'AEM user'

- name: ensure that root AEM directory is present
  file:
    path: '{{ aem_root }}'
    owner: '{{ aem_user }}'
    group: '{{ aem_user }}'
    mode: 0775
    state: directory

- name: ensure that directory for AEM home dir is present
  file:
    path: '{{ aem_home }}'
    owner: '{{ aem_user }}'
    group: '{{ aem_user }}'
    mode: 0775
    state: directory
