---
# file: tasks/remove-replication-agent.yml

- name: "Create/update agent for {{ hostvars[host]['inventory_hostname'] }} host"
  aem_agent:
    name: "{{ agent|replace('.','-')|lower() }}"
    state: absent
    folder: 'agents.author'
    admin_user: '{{ aem_admin_login }}'
    admin_password: '{{ aem_admin_password }}'
    host: "http://localhost"
    port: "{{ aem_instance_port }}"
