---
# file: tasks/set_facts.yml

- name: check if required variables are defined
  fail:
    msg: 'Variable {{ item }} should be defined!'
  when: item is undefined
  loop:
    - environment_type
    - aem_instance_type
    - aem_instance_port
    - aem_admin_login
    - aem_admin_password

- name: variables initialization
  set_fact:
    # AEM Home Dir: aem_root = /opt/aem/author(publish)
    aem_home: '{{ aem_root }}/{{ aem_instance_type }}'
    # AEM service name
    aem_service_name: 'aem-{{ aem_instance_type }}'

    # Destination file name
    cq_file_name: 'cq-{{ aem_instance_type }}-p{{ aem_instance_port }}'
    # AEM REST Link
#    aem_rest_link: 'http://{{ inventory_hostname }}:{{ aem_instance_port }}'
    aem_rest_link: 'http://localhost:{{ aem_instance_port }}'
#    aem_load_test_link: 'http://localhost:{{ aem_instance_port }}'


- name: variables initialization
  set_fact:
    aem_file: '/opt/{{ aem_service_name }}.done'
    tasks_path: '{{ role_path }}/tasks'

- name: reinitialization of defaults as variables
  set_fact:
    aem_version: '{{ aem_version }}'
    aem_packages: '{{ aem_packages }}'
    aem_no_sample_content: '{{ aem_no_sample_content }}'
    aem_custom_modes: '{{ aem_custom_modes }}'
    aem_root: '{{ aem_root }}'
    aem_user: '{{ aem_user }}'
    aem_group: '{{ aem_group }}'
    aem_user_id: '{{ aem_user_id }}'
    aem_group_id: '{{ aem_group_id }}'
    aem_change_default_admin_password: '{{ aem_change_default_admin_password }}'
    aem_groups: '{{ aem_groups }}'
    aem_users: '{{ aem_users }}'
    # For replication agents
    publishers: []
    # For flush agents
    renders: []
    dispatcher_w_renders: []
    base_agent_body: "retryDelay=60000&logLevel=error&serializationType=flush"

- name: prepare handlers content
  set_fact:
    aem_load_handler:
      -
        path: 'damadmin'
        content: 'Assets'
      -
        path: 'miscadmin'
        content: 'Tools'
      -
        path: 'system/console/bundles'
        content: 'Experience'
- name: prepare handlers content for 5.5
  set_fact:
    aem_load_handler:
      -
        path: 'damadmin'
        content: 'damadmin.infinity'
      -
        path: 'miscadmin'
        content: 'Tools'
      -
        path: 'system/console/bundles'
        content: '/system/console/productinfo'
  when: "aem_version == '5.5' or aem_version == 5.5"
