---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: azure
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-azure-centos7-aem-node-author-6.4-datastore
    platform: centos7
    vm_size: Standard_D2s_v3
    assign_public_ip: false
    az_location: northeurope
    az_resource_group_name: epm-ldi
    az_virtual_network_name: epm-ldi-northeurope-vnet
    az_subnet_name: epm-ldi-northeurope-subnet
    az_network_security_group: epm-ldi-northeurope-sg
    groups:
      - rhel_family
      - aem_authors
      - aem_publishers

  - name: test-azure-ubuntu16-aem-node-author-6.4-datastore
    platform: ubuntu16
    vm_size: Standard_D2s_v3
    assign_public_ip: false
    az_location: northeurope
    az_resource_group_name: epm-ldi
    az_virtual_network_name: epm-ldi-northeurope-vnet
    az_subnet_name: epm-ldi-northeurope-subnet
    az_network_security_group: epm-ldi-northeurope-sg
    groups:
      - debian_family
      - aem_authors
      - aem_publishers

  - name: test-azure-ubuntu18-aem-node-author-6.4-datastore
    platform: ubuntu18
    vm_size: Standard_D2s_v3
    assign_public_ip: false
    az_location: northeurope
    az_resource_group_name: epm-ldi
    az_virtual_network_name: epm-ldi-northeurope-vnet
    az_subnet_name: epm-ldi-northeurope-subnet
    az_network_security_group: epm-ldi-northeurope-sg
    groups:
      - debian_family
      - aem_authors
      - aem_publishers

provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer
  playbooks:
    create: ../resources/provisioning/AZURE/create.yml
    prepare: prepare.yml
    destroy: ../resources/provisioning/AZURE/destroy.yml
    verify: ../resources/tests/verify.yml
    cleanup: ../resources/cleanup/cleanup_azure.yml
  lint:
    name: ansible-lint
scenario:
  name: cloud-azure-direct-author-6.4-datastore
verifier:
  name: ansible
  lint:
    name: ansible-lint
