---
- name: Include common prepare
  import_playbook: ../resources/provisioning/AWS/prepare.yml

- name: Install java
  hosts: all
  roles:
    - role: lean_delivery.java
      java_distribution: oracle_java
      java_package: jdk
      java_major_version: 11
      transport: web
      transport_web: "{{ lookup('env','STORAGE_AWS') }}/oracle-java/jdk-11.0.2_linux-x64_bin.tar.gz"

- name: Prepare certificates
  hosts: all
  become: true
  roles:
    - role: jdauphant.ssl-certs
      ssl_certs_common_name: localhost
      ssl_certs_cert_path: "/etc/ssl/{{ ssl_certs_common_name }}/{{ ssl_certs_common_name }}.crt"
      ssl_certs_path_owner: "root"
      ssl_certs_path_group: "root"
