---
- name: Include common prepare
  import_playbook: ../resources/provisioning/AWS/prepare.yml

- name: Prepare temporary bucket for S3 data store testing
  hosts: aem_authors[0]
  tasks:
    block:
      - name: Define pyton-pip variables
        set_fact:
          pip_executable: "{{ ansible_os_family == 'Debian' | ternary('pip3', 'pip3') }}"
          python_executable: "{{ ansible_os_family == 'Debian' | ternary('python3', 'pip') }}"

      - name: Install python-pip
        package:
          name: '{{ requirements }}'
        retries: 3
        register: result
        until: result is success
        become: true

      - name: install python boto3
        pip:
          name: boto3
          executable: '{{ pip_executable }}'
        retries: 3
        register: result
        until: result is success
        become: true

      - name: Create S3 bucket
        aws_s3:
          bucket: "{{ lookup('env','CI_JOB_ID') }}"
          mode: create
          region: us-east-1

- name: Install java
  hosts: all
  roles:
    - role: lean_delivery.java
      java_distribution: oracle_java
      java_package: jdk
      java_major_version: 11
      transport: web
      transport_web: "{{ lookup('env','STORAGE_AWS') }}/oracle-java/jdk-11.0.2_linux-x64_bin.tar.gz"

- name: Prepare certificates
  hosts: all
  become: true
  roles:
    - role: jdauphant.ssl-certs
      ssl_certs_common_name: localhost
      ssl_certs_cert_path: "/etc/ssl/{{ ssl_certs_common_name }}/{{ ssl_certs_common_name }}.crt"
      ssl_certs_path_owner: "root"
      ssl_certs_path_group: "root"
