---
- name: Include common prepare
  import_playbook: ../resources/provisioning/AWS/prepare.yml

- name: Prepare temporary bucket for S3 data store testing
  hosts: aem_authors[0]
  tasks:
    - block:
      - name: Install EPEL repo
        yum:
          name: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm'
          state: present
        when: ansible_os_family == 'RedHat'
      - name: Add universe repository for Ubuntu
        apt_repository:
          repo: 'deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe'
          state: present
        when: ansible_distribution == 'Ubuntu'
      - name: Install python-pip
        package:
          name: "{{ (ansible_os_family == 'Debian') | ternary('python3-pip', 'python-pip') }}"
      - name: install python boto3
        pip:
          name: boto3
          executable: "{{ (ansible_os_family == 'Debian') | ternary('pip3', 'pip') }}"
      - name: Create S3 bucket
        aws_s3:
          bucket: "epm-ldi-aem-{{ lookup('env','CI_JOB_ID') }}"
          mode: create
          region: us-east-1
      become: true

- name: Install java
  hosts: all
  roles:
    - role: lean_delivery.java
      java_distribution: oracle_java
      java_package: jdk
      java_major_version: 11
      transport: web
      transport_web: "{{ lookup('env','STORAGE_AWS') }}/oracle-java/jdk-11.0.2_linux-x64_bin.tar.gz"

- name: Prepare certificates
  hosts: all
  become: true
  roles:
    - role: jdauphant.ssl-certs
      ssl_certs_common_name: localhost
      ssl_certs_cert_path: "/etc/ssl/{{ ssl_certs_common_name }}/{{ ssl_certs_common_name }}.crt"
      ssl_certs_path_owner: "root"
      ssl_certs_path_group: "root"
