---
- name: Get storage access keys
  hosts: localhost
  gather_facts: true
  connection: local
  vars:
    resource_group_name: epm-ldi
    storage_account_name: storage11490
  tasks:
    - name: get storage access keys
      azure_rm_resource:
        resource_group: "{{ resource_group_name }}"
        method: POST
        url: "/subscriptions/{{ lookup('env','AZURE_SUBSCRIPTION_ID') }}\
                   /resourceGroups/{{ resource_group_name }}/providers/\
                   Microsoft.Storage/storageAccounts/\
                   {{ storage_account_name }}/listKeys"
        body:
          api-version: "2019-06-01"
      register: storage_access_keys

- name: Install authors
  hosts: aem_authors
  roles:
    - role: ansible-role-aem-node
      download_transport: s3
      publisher_ssl: true
      aem_ssl_enable: true
      aem_ssl_dir: /etc/ssl/localhost/
      replication_enabled: true
      aem_instance_type: author
      web_transport_common_url: "{{ lookup('env','STORAGE_AWS') }}/aem"
      aem_change_default_admin_password: true
      aem_new_admin_password: "testtest_123@S"
      publishers: "{{ groups['aem_publishers'] }}"
      aem_version: '6.5'
      aem_groups:
       -
        id: 'test_group'
        name: 'Test'
        description: 'All test users'
        permissions:
          - 'path:/,read:true'
          - 'path:/etc/packages,read:true,modify:true,create:true,delete:false,replicate:true'
        root_groups:
          - 'everyone'
      aem_users:
       -
        category: 'test'
        id: 'test_user'
        first_name: 'Test'
        second_name: 'User'
        password: 'testtest_123i@S'
        group: 'test_group'
