---
- name: Include common prepare
  import_playbook: ../resources/provisioning/AZURE/prepare.yml

- name: Install java
  hosts: aem_authors
  pre_tasks:
    - name: Download java tarball from Storage Blob
      azure_rm_storageblob:
        resource_group: epm-ldi
        storage_account_name: storage11490
        container: oracle-java
        blob: jdk-11.0.3_linux-x64_bin.tar.gz
        dest: /tmp/jdk-11.0.3_linux-x64_bin.tar.gz

  roles:
    - role: lean_delivery.java
      java_distribution: oracle_java
      transport: local
      transport_local: /tmp/jdk-11.0.3_linux-x64_bin.tar.gz

- name: Prepare certificates
  hosts: aem_authors
  become: true
  roles:
    - role: jdauphant.ssl-certs
      ssl_certs_common_name: localhost
      ssl_certs_cert_path: "/etc/ssl/{{ ssl_certs_common_name }}/{{ ssl_certs_common_name }}.crt"
      ssl_certs_path_owner: "root"
      ssl_certs_path_group: "root"
