---

- name: java_install
  hosts: all
  roles:
    - role: lean_delivery.java


- name: publisher_install
  hosts: aem_publishers

  roles:
    - role: ansible-role-aem-node
      aem_instance_type: publish
      ftp_server_link: "{{ lookup('env','STORAGE_AWS') }}/aem"

      aem_groups:
       -
        id: 'test_group'
        name: 'Test'
        description: 'All test users'
        permissions:
          - 'path:/,read:true'
          - 'path:/etc/packages,read:true,modify:true,create:true,delete:false,replicate:true'
        root_group: 'everyone'
      aem_users:
       -
        category: 'test'
        id: 'test_user'
        first_name: 'Test'
        second_name: 'User'
        password: 'test_user_password'
        group: 'test_group'



